version: "3"
services:
#    redis:
#        image: redis:alpine
#        networks:
#            - app-network
    monitor:
        build:
            context: app
            args:
                PRODUCTION: 0

        entrypoint: "yarn run dev"

        volumes:
            - ../:/project

        networks:
            - app-network

networks:
    docker_app-network:
        external: true
